# FROM arm32v7/debian:bookworm
FROM balenalib/raspberrypi3-debian:bookworm

RUN apt-get update -y && \
    apt-get install -y \
        cmake \
        build-essential \
        gcc-arm-linux-gnueabihf \
        g++-arm-linux-gnueabihf \
        qt6-base-dev \
        qt6-webengine-dev

WORKDIR /app
