FROM balenalib/raspberry-pi:bookworm

RUN apt-get update -y && \
    apt-get install -y \
        cmake \
        gcc-arm-none-eabi \
        build-essential \
        qt6-base-dev \
        qt6-webengine-dev

WORKDIR /app
