FROM balenalib/raspberry-pi:bookworm

RUN apt-get update -y && \
    apt-get install -y \
        cmake \
        build-essential \
        build-essential \
        qt6-base-dev

# ENV CXX=/usr/bin/arm-none-eabi-g++
# ENV CC=/usr/bin/arm-none-eabi-gcc

WORKDIR /app
