# FROM arm32v7/debian:bookworm
FROM balenalib/raspberrypi4-64-debian:bookworm

RUN apt-get update -y && \
    apt-get install -y \
        cmake \
        build-essential \
        gcc-aarch64-linux-gnu \
        g++-aarch64-linux-gnu \
        qt6-base-dev \
        qt6-webengine-dev

ENV CXX=/usr/bin/aarch64-linux-gnu-g++

WORKDIR /app
